/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './index.html',
        './src/**/*.{ts,tsx,js,jsx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'outline-variant': '#c7c4d7',
                'on-primary-container': '#fffbff',
                'primary-fixed-dim': '#c0c1ff',
                'surface-container-lowest': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-primary-fixed': '#07006c',
                'secondary-container': '#6cf8bb',
                'on-tertiary-fixed-variant': '#3f465c',
                'on-tertiary-fixed': '#131b2e',
                'on-surface-variant': '#464554',
                'on-primary': '#ffffff',
                'surface-variant': '#d3e4fe',
                'surface-container': '#e5eeff',
                'surface-dim': '#cbdbf5',
                'inverse-surface': '#213145',
                'surface': '#f8f9ff',
                'tertiary-container': '#6c748b',
                'on-tertiary-container': '#fefcff',
                'secondary': '#006c49',
                'background': '#f8f9ff',
                'primary-container': '#6063ee',
                'surface-container-high': '#dce9ff',
                'on-primary-fixed-variant': '#2f2ebe',
                'surface-bright': '#f8f9ff',
                'error': '#ba1a1a',
                'secondary-fixed-dim': '#4edea3',
                'error-container': '#ffdad6',
                'secondary-fixed': '#6ffbbe',
                'on-error': '#ffffff',
                'on-secondary': '#ffffff',
                'tertiary': '#545c72',
                'inverse-on-surface': '#eaf1ff',
                'tertiary-fixed': '#dae2fd',
                'surface-tint': '#494bd6',
                'on-secondary-fixed': '#002113',
                'on-secondary-container': '#00714d',
                'primary': '#4648d4',
                'on-background': '#0b1c30',
                'surface-container-highest': '#d3e4fe',
                'surface-container-low': '#eff4ff',
                'tertiary-fixed-dim': '#bec6e0',
                'on-error-container': '#93000a',
                'primary-fixed': '#e1e0ff',
                'inverse-primary': '#c0c1ff',
                'on-surface': '#0b1c30',
                'on-secondary-fixed-variant': '#005236',
                'outline': '#767586',

                // Dashboard specific
                'dashboard-bg': '#f8f9ff',
                'card-bg': '#ffffff',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
            spacing: {
                'space-xs': '0.25rem',
                'space-lg': '1rem',
                'space-md': '0.75rem',
                'margin': '1rem',
                'space-xl': '1.5rem',
                'gutter': '0.75rem',
                'space-sm': '0.5rem',
            },
            fontFamily: {
                'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
                'label-mono': ['JetBrains Mono', 'monospace'],
                'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
                'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
                'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
                'body-md': ['Plus Jakarta Sans', 'sans-serif'],
                'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
                'label-md': ['Plus Jakarta Sans', 'sans-serif'],
                'badge-sm': ['Plus Jakarta Sans', 'sans-serif'],
                sans: ['Plus Jakarta Sans', 'sans-serif'],
            },
            fontSize: {
                'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'label-mono': ['11px', { lineHeight: '14px', letterSpacing: '-0.02em', fontWeight: '500' }],
                'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'body-lg': ['15px', { lineHeight: '22px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
                'badge-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.04em', fontWeight: '700' }],
            },
            animation: {
                'glow-pulse': 'glow-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'subtle-float': 'subtle-float 3s ease-in-out infinite',
                'fadeIn': 'fadeIn 0.2s ease-out',
                'scaleUp': 'scaleUp 0.2s ease-out',
                'slide-in': 'slideIn 0.3s ease-out',
            },
            keyframes: {
                'glow-pulse': {
                    '0%, 100%': { opacity: '1', filter: 'brightness(1)' },
                    '50%': { opacity: '0.8', filter: 'brightness(1.5)' },
                },
                'subtle-float': {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-5px)' },
                },
                'fadeIn': {
                    from: { opacity: '0' },
                    to: { opacity: '1' },
                },
                'scaleUp': {
                    from: { opacity: '0', transform: 'scale(0.95)' },
                    to: { opacity: '1', transform: 'scale(1)' },
                },
                'slideIn': {
                    from: { opacity: '0', transform: 'translateY(-8px)' },
                    to: { opacity: '1', transform: 'translateY(0)' },
                },
            },
        },
    },
    plugins: [],
};
