// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftSync.API.Data;

#nullable disable

namespace ShiftSync.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-user-id",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "role-admin-id"
                        },
                        new
                        {
                            UserId = "user-id-1",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-2",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-3",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-4",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-5",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-6",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-7",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-8",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-9",
                            RoleId = "role-user-id"
                        },
                        new
                        {
                            UserId = "user-id-10",
                            RoleId = "role-user-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-ADMIN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "System Admin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SHIFTSYNC.COM",
                            NormalizedUserName = "ADMIN@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJfropylbyoTYOQf2UlxRMapTVFNyKW6A9XwBy19rYxzFzG8iVDZd/MEAwazCyCGkw==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "STATIC-SECURITY-STAMP-ADMIN",
                            TwoFactorEnabled = false,
                            UserName = "admin@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user1@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 1",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@SHIFTSYNC.COM",
                            NormalizedUserName = "USER1@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMTxYc2jJMp6ry6CtBMplD3jdMXf7H/9MUgPRJp9HbCtrCARQpDHcv4InkhNsmm1VQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-1",
                            TwoFactorEnabled = false,
                            UserName = "user1@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user2@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 2",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@SHIFTSYNC.COM",
                            NormalizedUserName = "USER2@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIYA6PaYrYWwXLGzNadkdYpSer6YM+pIlLmvKPc4bAS7HmAau3WXff+PZEUjr8ODCg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-2",
                            TwoFactorEnabled = false,
                            UserName = "user2@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user3@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 3",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@SHIFTSYNC.COM",
                            NormalizedUserName = "USER3@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENUK9z7ygMpteFoLJxzZi4XBJcv+stgBFF+ab+gxi6fvNndlOYzgLZmY76hgF3GssQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-3",
                            TwoFactorEnabled = false,
                            UserName = "user3@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user4@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 4",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@SHIFTSYNC.COM",
                            NormalizedUserName = "USER4@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEI6pnVP5oeAsqXgm22sggvkgW95lT/DPl7f+1mpghUijLQfdkzZi+ObXRROGQ/qBOg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-4",
                            TwoFactorEnabled = false,
                            UserName = "user4@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-5",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user5@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 5",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@SHIFTSYNC.COM",
                            NormalizedUserName = "USER5@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG3R5/suLiTrKBhirDUfyjp/NbHn9+HFGAqvEAH9gxiIgPhIM5taTziO7gPI/Srqpw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-5",
                            TwoFactorEnabled = false,
                            UserName = "user5@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user6@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 6",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@SHIFTSYNC.COM",
                            NormalizedUserName = "USER6@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPICG5yCSDV1/79AVN1HbpHnqanjeMkkRYFIKPaLKiX5np+AF99mu45r1ysTo6xz6w==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-6",
                            TwoFactorEnabled = false,
                            UserName = "user6@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-7",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user7@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 7",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@SHIFTSYNC.COM",
                            NormalizedUserName = "USER7@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE5wBEjeZha2PiqRy0clIANvG7ZweWruLhqcQSsIpwY44y27mbQzXenbHEsneQABEg==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-7",
                            TwoFactorEnabled = false,
                            UserName = "user7@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user8@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 8",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@SHIFTSYNC.COM",
                            NormalizedUserName = "USER8@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENRkhKj2KXFZSl1pCHy8bqTz5cyZrIJKWf6bDW72GZp3AGfeZYJLZVVb3goTB4y94Q==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-8",
                            TwoFactorEnabled = false,
                            UserName = "user8@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-9",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user9@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 9",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@SHIFTSYNC.COM",
                            NormalizedUserName = "USER9@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPxja25BPsrVrV7g0vu+4ANnL51Y/MhydDOs3l/w1TLpKjl/6++R+/zXzZLk65+4SQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-9",
                            TwoFactorEnabled = false,
                            UserName = "user9@shiftsync.com"
                        },
                        new
                        {
                            Id = "user-id-10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-10",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user10@shiftsync.com",
                            EmailConfirmed = true,
                            FullName = "Employee 10",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER10@SHIFTSYNC.COM",
                            NormalizedUserName = "USER10@SHIFTSYNC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKZfvPTLTTrLV4pOLJYL8tcEvBM9UiZRZF04OgWTKKjFubVsW3tZVDsaH/3bf2KO6A==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "STATIC-SECURITY-STAMP-10",
                            TwoFactorEnabled = false,
                            UserName = "user10@shiftsync.com"
                        });
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CheckInLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CheckInLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserShiftId");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.AttendanceBreak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<int>("BreakTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("BreakTypeId");

                    b.ToTable("AttendanceBreaks", (string)null);
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.BreakType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxOccurrencesPerShift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BreakTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxDurationMinutes = 30,
                            MaxOccurrencesPerShift = 1,
                            Name = "Lunch Break"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxDurationMinutes = 15,
                            MaxOccurrencesPerShift = 2,
                            Name = "Coffee / Rest Break"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaxDurationMinutes = 15,
                            MaxOccurrencesPerShift = 2,
                            Name = "Prayer Break"
                        });
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAllowedBreaksDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<int>("MinActiveEmployeesRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            MaxAllowedBreaksDurationMinutes = 60,
                            MinActiveEmployeesRequired = 2,
                            Name = "Morning Shift",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.UserShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId", "ShiftId", "Date")
                        .IsUnique();

                    b.ToTable("UserShifts", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.Attendance", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSync.API.Models.Entities.UserShift", "UserShift")
                        .WithMany("Attendances")
                        .HasForeignKey("UserShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserShift");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.AttendanceBreak", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.Attendance", "Attendance")
                        .WithMany("Breaks")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftSync.API.Models.Entities.BreakType", "BreakType")
                        .WithMany("AttendanceBreaks")
                        .HasForeignKey("BreakTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("BreakType");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.UserShift", b =>
                {
                    b.HasOne("ShiftSync.API.Models.Entities.Shift", "Shift")
                        .WithMany("UserShifts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShiftSync.API.Models.Entities.ApplicationUser", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.Attendance", b =>
                {
                    b.Navigation("Breaks");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.BreakType", b =>
                {
                    b.Navigation("AttendanceBreaks");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.Shift", b =>
                {
                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("ShiftSync.API.Models.Entities.UserShift", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
